services:
  prefect:
    image: prefecthq/prefect:2.14-python3.11
    container_name: prefect
    working_dir: /app
    volumes:
      - ..:/app
    command: >
      bash -c "
      pip install pandas pyarrow &&
      python prefect/prefect_flow.py
      "
